import {
  ListTodo,
  ClipboardList,
  ClipboardCheck,
  ListChecks,
  CheckCircle2,
  Briefcase,
  Folder,
  Inbox,
  FileText,
  BookOpen,
  NotebookPen,
  Calendar,
  CalendarDays,
  Clock3,
  Timer,
  AlarmClock,
  Flag,
  Pin,
  Target,
  Star,
  Heart,
  HeartPulse,
  Stethoscope,
  Home,
  User,
  Users,
  Building2,
  Mail,
  Bell,
  Lightbulb,
  Rocket,
  Zap,
  Wrench,
  Settings,
  Laptop,
  Code2,
  Package,
  Truck,
  ShoppingCart,
  Wallet,
  Gauge,
  ChartNoAxesColumnIncreasing,
  ChartBar,
  ChartLine,
  Activity,
  Award,
  Trophy,
  ShieldCheck,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export const appIcons = {
  'list-todo': ListTodo,
  'clipboard-list': ClipboardList,
  'clipboard-check': ClipboardCheck,
  'list-checks': ListChecks,
  'check-circle': CheckCircle2,
  'briefcase': Briefcase,
  'folder': Folder,
  'inbox': Inbox,
  'file-text': FileText,
  'book-open': BookOpen,
  'notebook-pen': NotebookPen,
  'calendar': Calendar,
  'calendar-days': CalendarDays,
  'clock': Clock3,
  'timer': Timer,
  'alarm-clock': AlarmClock,
  'flag': Flag,
  'pin': Pin,
  'target': Target,
  'star': Star,
  'heart': Heart,
  'heart-pulse': HeartPulse,
  'stethoscope': Stethoscope,
  'home': Home,
  'user': User,
  'users': Users,
  'building-2': Building2,
  'mail': Mail,
  'bell': Bell,
  'lightbulb': Lightbulb,
  'rocket': Rocket,
  'zap': Zap,
  'wrench': Wrench,
  'settings': Settings,
  'laptop': Laptop,
  'code-2': Code2,
  'package': Package,
  'truck': Truck,
  'shopping-cart': ShoppingCart,
  'wallet': Wallet,
  'gauge': Gauge,
  'chart': ChartNoAxesColumnIncreasing,
  'chart-bar': ChartBar,
  'chart-line': ChartLine,
  'activity': Activity,
  'award': Award,
  'trophy': Trophy,
  'shield-check': ShieldCheck,
} satisfies Record<string, LucideIcon>

export type AppIconKey = keyof typeof appIcons
